import ArrowDown from '@/components/checkout/iconCheckOut/ArrowDown';
import React from 'react';

const Cundinamarca = ({ onChange }) => {
  const municipios = [
    "Agua de dios",
    "Alban",
    "Anapoima",
    "Anolaima",
    "Apulo",
    "Arbelaez",
    "Bituima",
    "Bojaca",
    "Briceño",
    "Cabrera",
    "Cachipay",
    "Cajicá",
    "Cambao",
    "Caparrapi",
    "Capellania",
    "Caqueza",
    "Carmen de carupa",
    "Cartagena",
    "Chaguani",
    "Chia",
    "Chinauta",
    "Chipaque",
    "Choachi",
    "Choconta",
    "Chusaca",
    "Cogua",
    "Cota",
    "Cucunuba",
    "El charquito",
    "El colegio mesitas",
    "El peñón",
    "El rosal",
    "El sisga",
    "El triunfo",
    "Facatativá",
    "Fomeque",
    "Fosca",
    "Funza",
    "Fuquene",
    "Fusagasuga",
    "Gachala",
    "Gachancipa",
    "Gacheta",
    "Gama",
    "Girardot",
    "Granada",
    "Guacheta",
    "Guaduas",
    "Guasca",
    "Guataqui",
    "Guatavita",
    "Guayabal de siquima",
    "Guayabetal",
    "Gutierrez",
    "Jerusalen",
    "Junin",
    "La calera",
    "La florida",
    "La gran via",
    "La mesa",
    "La palma",
    "La peña",
    "La punta",
    "La union",
    "La vega",
    "La victoria",
    "Lenguazaque",
    "Macheta",
    "Madrid",
    "Manta",
    "Maya",
    "Medina",
    "Mosquera",
    "Nariño",
    "Nemocon",
    "Nilo",
    "Nimaima",
    "Nocaima",
    "Pacho",
    "Paime",
    "Pandi",
    "Paratebueno",
    "Pasca",
    "Puente de piedra",
    "Puente quetame",
    "Puerto bogota",
    "Puerto salgar",
    "Puli",
    "Quebradanegra",
    "Quetame",
    "Quipile",
    "Ricaurte",
    "San ant de tequen",
    "San bernardo",
    "San cayetano",
    "San francisco",
    "San juan de rioseco",
    "Santandersito",
    "Sasaima",
    "Sesquile",
    "Sibate",
    "Silvania",
    "Simijaca",
    "Soacha",
    "Sopo",
    "Subachoque",
    "Subia",
    "Suesca",
    "Supata",
    "Susa",
    "Sutatausa",
    "Tabio",
    "Tausa",
    "Tena",
    "Tenjo",
    "Tibacuy",
    "Tibirita",
    "Tobia",
    "Tocaima",
    "Tocancipa",
    "Topaipi",
    "Tudela",
    "Ubala",
    "Ubaque",
    "Ubate",
    "Une",
    "Utica",
    "Venecia",
    "Vergara",
    "Viani",
    "Villagomez",
    "Villapinzon",
    "Villeta",
    "Viota",
    "Yacopi",
    "Zipacon",
    "Zipaquira"
  ];

  return (
    <div className="relative">
      <select
        name="Direccion1"
        id="Cundinamarca"
        className="city_select select2-hidden-accessible inline-block w-full appearance-none rounded border border-gray-400 bg-white bg-opacity-50 py-3 pl-3 pr-8 leading-tight text-gray-500 font-light text-[14px]"
        onChange={onChange}
      >
        <option value="">Por favor seleccione</option>
        {municipios.map((municipio, index) => (
          <option key={index} value={municipio}>{municipio}</option>
        ))}
      </select>
      <span
        className="absolute right-0 mr-1 text-[#111]"
        style={{ top: "25%" }}
      >
        <ArrowDown width={24} height={24} className="fill-current" />
      </span>
    </div>
  );
};

export default Cundinamarca;
